# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Walknut.ui'
#
# Created: Fri Apr  3 20:36:33 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
	_fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
	def _fromUtf8(s):
		return s

try:
	_encoding = QtGui.QApplication.UnicodeUTF8
	def _translate(context, text, disambig):
		return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
	def _translate(context, text, disambig):
		return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(QtGui.QMainWindow):
	def __init__(self):
		QtGui.QWidget.__init__(self)
		self.setupUi(self)
		
	def setupUi(self, MainWindow):
		MainWindow.setObjectName(_fromUtf8("MainWindow"))
		MainWindow.resize(1047, 655)
		self.centralwidget = QtGui.QWidget(MainWindow)
		self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
		self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
		self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
		self.horizontalLayout = QtGui.QHBoxLayout()
		self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
		self.pushButton_4 = QtGui.QPushButton(self.centralwidget)
		self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
		self.horizontalLayout.addWidget(self.pushButton_4)
		self.pushButton_5 = QtGui.QPushButton(self.centralwidget)
		self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
		self.horizontalLayout.addWidget(self.pushButton_5)
		spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout.addItem(spacerItem)
		self.verticalLayout.addLayout(self.horizontalLayout)
		self.tabWidget = QtGui.QTabWidget(self.centralwidget)
		self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
		self.tab_2 = QtGui.QWidget()
		self.tab_2.setObjectName(_fromUtf8("tab_2"))
		self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_2)
		self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
		self.graphicsView = QtGui.QGraphicsView(self.tab_2)
		self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
		self.verticalLayout_3.addWidget(self.graphicsView)
		self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
		self.tab_1 = QtGui.QWidget()
		self.tab_1.setObjectName(_fromUtf8("tab_1"))
		self.gridLayout_8 = QtGui.QGridLayout(self.tab_1)
		self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
		self.tabWidget_2 = QtGui.QTabWidget(self.tab_1)
		self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
		self.tab = QtGui.QWidget()
		self.tab.setObjectName(_fromUtf8("tab"))
		self.gridLayout_3 = QtGui.QGridLayout(self.tab)
		self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
		self.gridLayout = QtGui.QGridLayout()
		self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
		self.label_3 = QtGui.QLabel(self.tab)
		self.label_3.setObjectName(_fromUtf8("label_3"))
		self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
		self.label = QtGui.QLabel(self.tab)
		self.label.setObjectName(_fromUtf8("label"))
		self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
		self.label_2 = QtGui.QLabel(self.tab)
		self.label_2.setObjectName(_fromUtf8("label_2"))
		self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
		spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.gridLayout.addItem(spacerItem1, 0, 2, 3, 1)
		self.doubleSpinBox_8 = QtGui.QDoubleSpinBox(self.tab)
		self.doubleSpinBox_8.setSingleStep(0.05)
		self.doubleSpinBox_8.setObjectName(_fromUtf8("doubleSpinBox_8"))
		self.gridLayout.addWidget(self.doubleSpinBox_8, 0, 1, 1, 1)
		self.doubleSpinBox_9 = QtGui.QDoubleSpinBox(self.tab)
		self.doubleSpinBox_9.setSingleStep(0.05)
		self.doubleSpinBox_9.setObjectName(_fromUtf8("doubleSpinBox_9"))
		self.gridLayout.addWidget(self.doubleSpinBox_9, 1, 1, 1, 1)
		self.doubleSpinBox_10 = QtGui.QDoubleSpinBox(self.tab)
		self.doubleSpinBox_10.setSingleStep(0.05)
		self.doubleSpinBox_10.setObjectName(_fromUtf8("doubleSpinBox_10"))
		self.gridLayout.addWidget(self.doubleSpinBox_10, 2, 1, 1, 1)
		self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
		self.gridLayout_6 = QtGui.QGridLayout()
		self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
		spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.gridLayout_6.addItem(spacerItem2, 0, 1, 1, 1)
		self.pushButton = QtGui.QPushButton(self.tab)
		self.pushButton.setObjectName(_fromUtf8("pushButton"))
		self.gridLayout_6.addWidget(self.pushButton, 0, 0, 1, 1)
		self.gridLayout_3.addLayout(self.gridLayout_6, 4, 0, 1, 1)
		self.gridLayout_7 = QtGui.QGridLayout()
		self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
		self.label_6 = QtGui.QLabel(self.tab)
		self.label_6.setObjectName(_fromUtf8("label_6"))
		self.gridLayout_7.addWidget(self.label_6, 1, 0, 1, 1)
		self.label_4 = QtGui.QLabel(self.tab)
		self.label_4.setObjectName(_fromUtf8("label_4"))
		self.gridLayout_7.addWidget(self.label_4, 0, 0, 1, 1)
		self.doubleSpinBox_11 = QtGui.QDoubleSpinBox(self.tab)
		self.doubleSpinBox_11.setMaximum(1.0)
		self.doubleSpinBox_11.setSingleStep(0.05)
		self.doubleSpinBox_11.setObjectName(_fromUtf8("doubleSpinBox_11"))
		self.gridLayout_7.addWidget(self.doubleSpinBox_11, 0, 1, 1, 1)
		self.doubleSpinBox_12 = QtGui.QDoubleSpinBox(self.tab)
		self.doubleSpinBox_12.setMaximum(1.0)
		self.doubleSpinBox_12.setSingleStep(0.05)
		self.doubleSpinBox_12.setObjectName(_fromUtf8("doubleSpinBox_12"))
		self.gridLayout_7.addWidget(self.doubleSpinBox_12, 1, 1, 1, 1)
		spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.gridLayout_7.addItem(spacerItem3, 0, 2, 1, 1)
		self.gridLayout_3.addLayout(self.gridLayout_7, 2, 0, 1, 1)
		spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		self.gridLayout_3.addItem(spacerItem4, 3, 0, 1, 1)
		self.line = QtGui.QFrame(self.tab)
		self.line.setFrameShape(QtGui.QFrame.HLine)
		self.line.setFrameShadow(QtGui.QFrame.Sunken)
		self.line.setObjectName(_fromUtf8("line"))
		self.gridLayout_3.addWidget(self.line, 1, 0, 1, 1)
		self.tabWidget_2.addTab(self.tab, _fromUtf8(""))
		self.tab_3 = QtGui.QWidget()
		self.tab_3.setObjectName(_fromUtf8("tab_3"))
		self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_3)
		self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
		self.label_28 = QtGui.QLabel(self.tab_3)
		self.label_28.setObjectName(_fromUtf8("label_28"))
		self.verticalLayout_4.addWidget(self.label_28)
		self.label_5 = QtGui.QLabel(self.tab_3)
		self.label_5.setObjectName(_fromUtf8("label_5"))
		self.verticalLayout_4.addWidget(self.label_5)
		spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		self.verticalLayout_4.addItem(spacerItem5)
		self.gridLayout_2 = QtGui.QGridLayout()
		self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
		self.doubleSpinBox_5 = QtGui.QDoubleSpinBox(self.tab_3)
		self.doubleSpinBox_5.setObjectName(_fromUtf8("doubleSpinBox_5"))
		self.gridLayout_2.addWidget(self.doubleSpinBox_5, 7, 3, 1, 1)
		self.doubleSpinBox_3 = QtGui.QDoubleSpinBox(self.tab_3)
		self.doubleSpinBox_3.setObjectName(_fromUtf8("doubleSpinBox_3"))
		self.gridLayout_2.addWidget(self.doubleSpinBox_3, 5, 3, 1, 1)
		self.label_20 = QtGui.QLabel(self.tab_3)
		self.label_20.setObjectName(_fromUtf8("label_20"))
		self.gridLayout_2.addWidget(self.label_20, 9, 0, 1, 1)
		self.label_19 = QtGui.QLabel(self.tab_3)
		self.label_19.setObjectName(_fromUtf8("label_19"))
		self.gridLayout_2.addWidget(self.label_19, 8, 0, 1, 1)
		spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.gridLayout_2.addItem(spacerItem6, 5, 5, 1, 1)
		self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.tab_3)
		self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
		self.gridLayout_2.addWidget(self.doubleSpinBox_2, 4, 3, 1, 1)
		self.doubleSpinBox_7 = QtGui.QDoubleSpinBox(self.tab_3)
		self.doubleSpinBox_7.setObjectName(_fromUtf8("doubleSpinBox_7"))
		self.gridLayout_2.addWidget(self.doubleSpinBox_7, 9, 3, 1, 1)
		self.label_14 = QtGui.QLabel(self.tab_3)
		self.label_14.setObjectName(_fromUtf8("label_14"))
		self.gridLayout_2.addWidget(self.label_14, 2, 0, 1, 1)
		self.label_12 = QtGui.QLabel(self.tab_3)
		self.label_12.setObjectName(_fromUtf8("label_12"))
		self.gridLayout_2.addWidget(self.label_12, 5, 0, 1, 1)
		self.doubleSpinBox_6 = QtGui.QDoubleSpinBox(self.tab_3)
		self.doubleSpinBox_6.setObjectName(_fromUtf8("doubleSpinBox_6"))
		self.gridLayout_2.addWidget(self.doubleSpinBox_6, 8, 3, 1, 1)
		self.label_11 = QtGui.QLabel(self.tab_3)
		self.label_11.setObjectName(_fromUtf8("label_11"))
		self.gridLayout_2.addWidget(self.label_11, 3, 0, 1, 1)
		self.label_13 = QtGui.QLabel(self.tab_3)
		self.label_13.setObjectName(_fromUtf8("label_13"))
		self.gridLayout_2.addWidget(self.label_13, 4, 0, 1, 1)
		self.label_18 = QtGui.QLabel(self.tab_3)
		self.label_18.setObjectName(_fromUtf8("label_18"))
		self.gridLayout_2.addWidget(self.label_18, 7, 0, 1, 1)
		self.label_17 = QtGui.QLabel(self.tab_3)
		self.label_17.setObjectName(_fromUtf8("label_17"))
		self.gridLayout_2.addWidget(self.label_17, 6, 0, 1, 1)
		self.doubleSpinBox_4 = QtGui.QDoubleSpinBox(self.tab_3)
		self.doubleSpinBox_4.setObjectName(_fromUtf8("doubleSpinBox_4"))
		self.gridLayout_2.addWidget(self.doubleSpinBox_4, 6, 3, 1, 1)
		self.label_15 = QtGui.QLabel(self.tab_3)
		self.label_15.setObjectName(_fromUtf8("label_15"))
		self.gridLayout_2.addWidget(self.label_15, 2, 3, 1, 1)
		self.doubleSpinBox = QtGui.QDoubleSpinBox(self.tab_3)
		self.doubleSpinBox.setSingleStep(0.1)
		self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
		self.gridLayout_2.addWidget(self.doubleSpinBox, 3, 3, 1, 1)
		self.verticalLayout_4.addLayout(self.gridLayout_2)
		self.line_2 = QtGui.QFrame(self.tab_3)
		self.line_2.setFrameShape(QtGui.QFrame.HLine)
		self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
		self.line_2.setObjectName(_fromUtf8("line_2"))
		self.verticalLayout_4.addWidget(self.line_2)
		self.horizontalLayout_4 = QtGui.QHBoxLayout()
		self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
		self.pushButton_3 = QtGui.QPushButton(self.tab_3)
		self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
		self.horizontalLayout_4.addWidget(self.pushButton_3)
		spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_4.addItem(spacerItem7)
		self.verticalLayout_4.addLayout(self.horizontalLayout_4)
		spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
		self.verticalLayout_4.addItem(spacerItem8)
		self.horizontalLayout_2 = QtGui.QHBoxLayout()
		self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
		self.pushButton_2 = QtGui.QPushButton(self.tab_3)
		self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
		self.horizontalLayout_2.addWidget(self.pushButton_2)
		spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
		self.horizontalLayout_2.addItem(spacerItem9)
		self.verticalLayout_4.addLayout(self.horizontalLayout_2)
		self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
		self.gridLayout_8.addWidget(self.tabWidget_2, 0, 0, 1, 1)
		self.tabWidget.addTab(self.tab_1, _fromUtf8(""))
		self.verticalLayout.addWidget(self.tabWidget)
		MainWindow.setCentralWidget(self.centralwidget)
		self.menubar = QtGui.QMenuBar(MainWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 1047, 25))
		self.menubar.setNativeMenuBar(False)
		self.menubar.setObjectName(_fromUtf8("menubar"))
		self.menuFile = QtGui.QMenu(self.menubar)
		self.menuFile.setObjectName(_fromUtf8("menuFile"))
		MainWindow.setMenuBar(self.menubar)
		self.statusbar = QtGui.QStatusBar(MainWindow)
		self.statusbar.setObjectName(_fromUtf8("statusbar"))
		MainWindow.setStatusBar(self.statusbar)
		self.menubar.addAction(self.menuFile.menuAction())

		self.retranslateUi(MainWindow)
		self.tabWidget.setCurrentIndex(0)
		self.tabWidget_2.setCurrentIndex(1)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

	def retranslateUi(self, MainWindow):
		MainWindow.setWindowTitle(_translate("MainWindow", "Walknut", None))
		self.pushButton_4.setText(_translate("MainWindow", "Disconnect", None))
		self.pushButton_5.setText(_translate("MainWindow", "Quick Connect", None))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Plot", None))
		self.label_3.setText(_translate("MainWindow", "Kd", None))
		self.label.setText(_translate("MainWindow", "Kp", None))
		self.label_2.setText(_translate("MainWindow", "Ki", None))
		self.pushButton.setText(_translate("MainWindow", "Apply", None))
		self.label_6.setText(_translate("MainWindow", "Derivative FIlter", None))
		self.label_4.setText(_translate("MainWindow", "Integral FIlter", None))
		self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("MainWindow", "PID", None))
		self.label_28.setText(_translate("MainWindow", "Sensor 1 is the one furthest out and 7 most in. ", None))
		self.label_5.setText(_translate("MainWindow", "Sensors on the other side will be set symmetrically.", None))
		self.label_20.setText(_translate("MainWindow", "7", None))
		self.label_19.setText(_translate("MainWindow", "6", None))
		self.label_14.setText(_translate("MainWindow", "Sensor", None))
		self.label_12.setText(_translate("MainWindow", "3", None))
		self.label_11.setText(_translate("MainWindow", "1", None))
		self.label_13.setText(_translate("MainWindow", "2", None))
		self.label_18.setText(_translate("MainWindow", "5", None))
		self.label_17.setText(_translate("MainWindow", "4", None))
		self.label_15.setText(_translate("MainWindow", "Value", None))
		self.pushButton_3.setText(_translate("MainWindow", "Calibrate Sensors For White", None))
		self.pushButton_2.setText(_translate("MainWindow", "Apply", None))
		self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("MainWindow", "Sensors", None))
		self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Parameters", None))
		self.menuFile.setTitle(_translate("MainWindow", "File", None))

if __name__ == "__main__":
	import sys
	app = QtGui.QApplication(sys.argv)
	ex = Ui_MainWindow()
	ex.show()
	sys.exit(app.exec_())